DATALOADER:
  TRAIN:
    BATCH_SIZE: 64
  TEST:
    BATCH_SIZE: 64
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.01
  MAX_EPOCH: 50
  LR_SCHEDULER: "StepLR"
  STEP_SIZE: 16
  WARMUP_TYPE: "none"

TRAIN:
  PRINT_FREQ: 5

MODEL:
  NAME: BOLD
  BOLD:
    # BACKBONE: "RN50"
    BACKBONE: "ViT-B/32"
    DOMAIN_LOSS_WEIGHT: 0.1
    ADAPTER_RATIO: 0.2
    STUDENT_NETWORK: "resnet18"
    # STUDENT_NETWORK: "resnet50"
    LOSS_WEIGHT:
      DISTILLATION: 0.20
      CLASSIFICATION: 0.60
    TEMPERATURE: 3.0
